const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const vm=require('node:vm');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const imports=require('../src/lib/contentImport.ts'),generation=require('../src/lib/contentGeneration.ts'),pipeline=require('../src/lib/contentPipeline.ts');
function fixture(admin=true){const rows=[],issues=[];let locks=0;const tx={$queryRaw:async()=>{locks++;return[];},mCQQuestion:{findMany:async()=>rows,create:async({data})=>{const row={id:'q'+rows.length,...data};rows.push(row);return row;}},questionImportIssue:{findMany:async()=>issues,create:async({data})=>issues.push(data)}};const prisma={...tx,questionSet:{findUnique:async({where,include})=>where.id==='pool'?{id:'pool',...(include?{questions:rows}:{})}:null},$transaction:async fn=>fn(tx)};
 const load=file=>{const module={exports:{}};const source=ts.transpileModule(fs.readFileSync(require.resolve(file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const deps={'next/server':{NextResponse:{json:(d,o)=>Response.json(d,o)}},'@/app/api/_lib/adminGuard':{requireAdminRequest:async()=>admin?{ok:true}:{ok:false,response:Response.json({error:'Forbidden'},{status:403})}},'@/lib/prisma':{prisma},'@/lib/contentImport':imports,'@/lib/contentGeneration':generation,'@/lib/contentPipeline':pipeline,'@/lib/contentApiError':{contentApiError:()=>''}};vm.runInNewContext(source,{module,exports:module.exports,require:name=>deps[name],Request,URL,console});return module.exports;};return {load,rows,issues,get locks(){return locks;}};}
const block={schemaVersion:2,id:'source',setName:'Sample',industry:'Sales',careerPath:'Account Executive',lane:'TRAINING',difficulty:2,facts:[{subject:'Example service',statement:'Example service manages requests.',answer:'Request management',distractors:['Storage administration','Report scheduling','Access monitoring'],explanation:'The source assigns request management to Example service.'}]};
const req=body=>new Request('https://example.test/api/admin/questions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
test('preview is read-only and reimport inserts once under a pool lock with duplicates preserved',async()=>{const f=fixture();const preview=f.load('../src/app/api/admin/content-preview/route.ts');let response=await preview.POST(req({setId:'pool',questions:[block,block]}));let report=await response.json();assert.equal(report.willInsert,1);assert.equal(report.duplicates,1);assert.equal(f.rows.length,0);assert.equal(f.locks,0);
 const route=f.load('../src/app/api/admin/questions/route.ts');response=await route.POST(req({setId:'pool',questions:[block,block]}));report=await response.json();assert.equal(report.inserted,1);assert.equal(report.skippedDuplicates,1);assert.equal(f.rows.length,1);assert.equal(f.rows[0].data.reviewStatus,'PENDING');assert.equal(f.issues.length,1);assert.equal(f.locks,1);
 await route.POST(req({setId:'pool',questions:[block]}));assert.equal(f.rows.length,1);assert.equal(f.issues.length,2);assert.equal(f.locks,2);
 response=await preview.POST(req({setId:'pool',questions:[block]}));report=await response.json();assert.equal(report.willInsert,0);assert.equal(report.duplicates,1);
});
test('non-admin requests cannot preview or import content',async()=>{const f=fixture(false);for(const file of ['../src/app/api/admin/content-preview/route.ts','../src/app/api/admin/questions/route.ts']){const response=await f.load(file).POST(req({setId:'pool',questions:[block]}));assert.equal(response.status,403);}assert.equal(f.rows.length,0);assert.equal(f.locks,0);});
