const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const vm=require('node:vm');
function load(file,deps,extra={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve(file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>deps[n],process:{env:{OPENAI_API_KEY:'server-only-test-key'}},Date,Response,Request,AbortSignal,...extra});return module.exports;}
const feedback={reply:'Check the service logs.',nextQuestion:'What would you check next?',scores:{technical:4,reasoning:3,communication:4,safety:5},strengths:['Safe approach'],improvements:['Explain the evidence'],exampleAnswer:'I would check the logs before making changes.'};
test('provider uses server credentials and strict Responses schema, sends only subject/transcript and caps the interview',async()=>{
 let request;const ai=load('../src/lib/techInterviewAI.ts',{'zod':require('zod')},{fetch:async(url,options)=>{request={url,options};return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(feedback)}]}]});}});
 const reply=await ai.askTechInterviewer({role:'Cloud Engineer',industry:'IT',level:'Senior',turn:6,history:[{speaker:'CANDIDATE',content:'Check logs'}]});assert.equal(reply.nextQuestion,null);assert.equal(ai.interviewScore(reply.scores),.8);
 const body=JSON.parse(request.options.body);assert.equal(request.url,'https://api.openai.com/v1/responses');assert.equal(request.options.headers.Authorization,'Bearer server-only-test-key');assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.equal(body.text.format.schema.additionalProperties,false);assert.equal(JSON.parse(body.input[0].content).role,'Cloud Engineer');assert.ok(!body.instructions.includes('Cloud Engineer'));
});
test('AI failure, refusal and malformed scoring never become fabricated feedback',async()=>{
 for(const response of [Response.json({}, {status:503}),Response.json({status:'completed',output:[{content:[{type:'refusal',refusal:'No'}]}]}),Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({...feedback,scores:{...feedback.scores,technical:99}})}]}]})]){const ai=load('../src/lib/techInterviewAI.ts',{'zod':require('zod')},{fetch:async()=>response});await assert.rejects(()=>ai.askTechInterviewer({role:'Helpdesk',industry:'IT',level:'Entry',turn:1,history:[]}));}
});
function fixture(){let aiCalls=0,notifications=0,writes=0;const session={id:'s',userId:'owner',kind:'TECH',status:'IN_PROGRESS',summary:JSON.stringify({simulatorVersion:1,role:'Help Desk',industry:'IT',level:'Entry level',turn:0,nextQuestion:'How do you troubleshoot?'}),turns:[{speaker:'INTERVIEWER',content:'How do you troubleshoot?',turnIndex:0,breakdownJson:{}}]};
 const db={$queryRaw:async()=>[],user:{findUnique:async()=>({selectedCareerPath:'Help Desk'})},interviewSession:{findFirst:async({where})=>where.userId===session.userId?session:null,findUnique:async()=>session,update:async({data})=>{Object.assign(session,data);return session;}},interviewTurn:{create:async({data})=>{writes++;session.turns.push(data);return data;}},notification:{create:async()=>{notifications++;}}};db.$transaction=async fn=>fn(db);
 let fail=false;const service=load('../src/lib/techInterviewSession.ts',{'@/lib/prisma':{prisma:db},'@/lib/auth/session':{getSessionUser:async()=>({id:'owner'})},'./techInterviewAI':{MAX_INTERVIEW_TURNS:6,interviewScore:s=>Object.values(s).reduce((a,b)=>a+b,0)/20,askTechInterviewer:async input=>{aiCalls++;if(fail)throw Error('Provider down');return {...feedback,nextQuestion:input.turn===6?null:feedback.nextQuestion};}}});return{service,session,fail:()=>fail=true,counts:()=>({aiCalls,notifications,writes})};}
test('foreign sessions and stale submissions are rejected before spending an AI call',async()=>{const f=fixture();await assert.rejects(()=>f.service.answerTechInterview('other',{sessionId:'s',answer:'Check logs',requestId:'x',expectedTurn:0}),/not found/);await assert.rejects(()=>f.service.answerTechInterview('owner',{sessionId:'s',answer:'Check logs',requestId:'x',expectedTurn:1}),/earlier question/);assert.equal(f.counts().aiCalls,0);});
test('answer replay is idempotent and AI failure preserves the question without appending turns',async()=>{const f=fixture(),input={sessionId:'s',answer:'Check logs',requestId:'x',expectedTurn:0};await f.service.answerTechInterview('owner',input);await f.service.answerTechInterview('owner',input);assert.deepEqual(f.counts(),{aiCalls:1,notifications:0,writes:2});assert.equal(JSON.parse(f.session.summary).turn,1);f.fail();await assert.rejects(()=>f.service.answerTechInterview('owner',{...input,requestId:'y',expectedTurn:1}),/Provider down/);assert.equal(f.counts().writes,2);assert.equal(JSON.parse(f.session.summary).turn,1);});
test('active interviews resume without a provider call, reports require six answers and completion notifies once',async()=>{const f=fixture();assert.equal((await f.service.beginTechInterview('owner',{level:'Entry level'})).id,'s');assert.equal(f.counts().aiCalls,0);await assert.rejects(()=>f.service.finishTechInterview('owner','s'),/Complete all/);for(let turn=0;turn<6;turn++)await f.service.answerTechInterview('owner',{sessionId:'s',answer:'Check logs',requestId:String(turn),expectedTurn:turn});const result=await f.service.finishTechInterview('owner','s');assert.equal(result.status,'FINISHED');assert.equal(result.pass,true);assert.equal(result.performance.criteria.technical,4);await f.service.finishTechInterview('owner','s');assert.equal(f.counts().notifications,1);});
test('tech routes authenticate and ignore forged client user IDs',async()=>{let signedIn=false,captured;const route=load('../src/app/api/interviews/tech/start/route.ts',{'zod':require('zod'),'@/lib/techInterviewSession':{techSessionUser:async()=>signedIn?{id:'real-owner'}:null,beginTechInterview:async(id,body)=>{captured={id,body};return{id:'s'};}}});const request=()=>new Request('https://app.test/api/interviews/tech/start',{method:'POST',body:JSON.stringify({userId:'victim',role:'Cloud Engineer'})});assert.equal((await route.POST(request())).status,401);signedIn=true;assert.equal((await route.POST(request())).status,200);assert.equal(captured.id,'real-owner');assert.equal(captured.body.level,'Entry level');assert.equal(captured.body.userId,undefined);});
test('conversation UI preserves a failed answer and retries the same request ID before advancing',async()=>{
 const React=require('react'),Renderer=require('react-test-renderer');let fail=true;const requests=[];
 const session={id:'s',role:'Help Desk',industry:'IT',level:'Entry level',status:'IN_PROGRESS',turn:0,maxTurns:6,nextQuestion:'How would you troubleshoot?',transcript:[{speaker:'INTERVIEWER',content:'How would you troubleshoot?'}]};
 const mockFetch=async(url,options)=>{if(url.endsWith('/career'))return Response.json({career:null});if(url.endsWith('/status'))return Response.json({configured:true,session});const body=JSON.parse(options.body);requests.push(body);if(fail)return Response.json({error:'Provider unavailable; retry.'},{status:503});return Response.json({session:{...session,turn:1,nextQuestion:'What next?',transcript:[...session.transcript,{speaker:'CANDIDATE',content:body.answer,feedback},{speaker:'INTERVIEWER',content:'What next?'}]}});};
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve('../src/components/TechInterviewSimulator.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,{module,exports:module.exports,require:n=>n==='react'?React:n==='react/jsx-runtime'?require(n):n==='next/link'?({children,...props})=>React.createElement('a',props,children):{},fetch:mockFetch,crypto:require('crypto').webcrypto});
 let renderer;await Renderer.act(async()=>{renderer=Renderer.create(React.createElement(module.exports.default));});
 await Renderer.act(async()=>renderer.root.findByType('textarea').props.onChange({target:{value:'I would inspect the logs and confirm connectivity.'}}));
 await Renderer.act(async()=>renderer.root.findByType('form').props.onSubmit({preventDefault(){}}));assert.match(renderer.root.findByProps({role:'alert'}).children.join(''),/Provider unavailable/);assert.equal(renderer.root.findByType('textarea').props.value,'I would inspect the logs and confirm connectivity.');
 fail=false;await Renderer.act(async()=>renderer.root.findByType('form').props.onSubmit({preventDefault(){}}));assert.equal(requests.length,2);assert.equal(requests[0].requestId,requests[1].requestId);assert.equal(renderer.root.findByType('textarea').props.value,'');assert.ok(JSON.stringify(renderer.toJSON()).includes('What next?'));assert.ok(JSON.stringify(renderer.toJSON()).includes('Review answer coaching'));await Renderer.act(async()=>renderer.unmount());
});
