"use client";

import { useEffect, useMemo, useState } from "react";
import { hydrateAuthenticatedUser, resolveClientUserId } from "@/lib/activeUser";
import { jsPDF } from "jspdf";

type Session = { id: string; status: string; startedAt: string };
type Offer = { id: string; title: string; salaryText: string; companyName: string; roleLabel: string; createdAt: string };

function msToClock(ms: number) {
  const s = Math.max(0, Math.floor(ms / 1000));
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}:${r.toString().padStart(2, "0")}`;
}

export default function TechInterviewPage() {
  const userId = resolveClientUserId();
  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    hydrateAuthenticatedUser().catch(() => {});
  }, []);
  const [question, setQuestion] = useState<string>("");
  const [answer, setAnswer] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [log, setLog] = useState<string[]>([]);

  const [pendingOffer, setPendingOffer] = useState(false);
  const [offerReadyAt, setOfferReadyAt] = useState<number | null>(null);
  const [offer, setOffer] = useState<Offer | null>(null);
  const [showCongrats, setShowCongrats] = useState(false);

  const remainingMs = useMemo(() => (offerReadyAt ? offerReadyAt - Date.now() : 0), [offerReadyAt]);
  const canDownload = Boolean(offer);

  useEffect(() => {
    if (!offerReadyAt) return;
    const t = setInterval(() => {
      // force rerender
      if (Date.now() >= offerReadyAt) {
        setShowCongrats(true);
        setPendingOffer(false);
      }
    }, 1000);
    return () => clearInterval(t);
  }, [offerReadyAt]);

  async function start() {
    setLoading(true);
    try {
      const res = await fetch("/api/interviews/tech/start", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ userId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Failed");
      setSession(data.session);
      setQuestion(data.nextQuestion);
      setLog((l) => [...l, "Tech interview started."]);
    } catch (e: any) {
      console.error(e.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  async function submitTurn() {
    if (!session) return;
    setLoading(true);
    try {
      const res = await fetch("/api/interviews/tech/turn", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ sessionId: session.id, answer }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Failed");
      setLog((l) => [...l, `You: ${answer}`, `Tech Lead: ${data.nextQuestion}`]);
      setAnswer("");
      setQuestion(data.nextQuestion);
    } catch (e: any) {
      console.error(e.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  async function fetchLatestOffer() {
    const res = await fetch(`/api/offers/latest?userId=${encodeURIComponent(userId)}`);
    const data = await res.json();
    if (res.ok) setOffer(data.offer ?? null);
  }

  async function finish() {
    if (!session) return;
    setLoading(true);
    try {
      const res = await fetch("/api/interviews/tech/finish", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ sessionId: session.id }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Failed");

      setLog((l) => [...l, `Result: ${data.pass ? "PASS ✅" : "FAIL ❌"} — ${data.summary}`]);
      setSession(null);
      setQuestion("");

      if (data.pass) {
        // "Offer processing" delay of 10 minutes (as requested).
        const readyAt = Date.now() + 10 * 60 * 1000;
        setOfferReadyAt(readyAt);
        setPendingOffer(true);

        // Offer is created immediately server-side; we can fetch now and show later.
        await fetchLatestOffer();
      }
    } catch (e: any) {
      console.error(e.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  function downloadPDF() {
    if (!offer) return;
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Mock Job Offer", 20, 22);

    doc.setFontSize(12);
    doc.text(`Company: ${offer.companyName}`, 20, 36);
    doc.text(`Role: ${offer.roleLabel}`, 20, 44);
    doc.text(`Title: ${offer.title}`, 20, 52);
    doc.text(`Compensation: ${offer.salaryText}`, 20, 60);
    doc.text(`Issued: ${new Date(offer.createdAt).toLocaleString()}`, 20, 68);

    doc.setFontSize(10);
    doc.text("This is a simulated offer generated by LevelUp Pro for practice and motivation.", 20, 86);
    doc.text("It is not an employment contract and does not guarantee a real job.", 20, 94);

    doc.save("LevelUpTech-Mock-Offer.pdf");
  }


  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ fontSize: 28, fontWeight: 900 }}>Mock Tech Interview (Legacy Page)</h1>
      <p style={{ opacity: 0.75, marginTop: 6 }}>Use the Dashboard modals for the Diablo-style interview experience.</p>
    </div>
  );
}
