'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import './tech-interview.css';
type Feedback={scores:Record<string,number>;strengths:string[];improvements:string[];exampleAnswer:string};
type Session={id:string;status:string;role:string;industry:string;level:string;turn:number;maxTurns:number;nextQuestion:string|null;scoreAvg:number|null;performance:{summary:string;strengths:string[];improvements:string[];criteria:Record<string,number>}|null;transcript:{speaker:string;content:string;feedback?:Feedback}[]};
async function api(path:string,body?:unknown){const response=await fetch(`/api/interviews/tech/${path}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error || 'Interview request failed. Please retry.');return data;}
export default function TechInterviewSimulator(){
  const [session,setSession]=useState<Session|null>(null),[role,setRole]=useState('Help Desk Technician'),[industry,setIndustry]=useState('Information Technology'),[level,setLevel]=useState('Entry level'),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(true),[configured,setConfigured]=useState(true),[signedIn,setSignedIn]=useState(true);
  const mounted=useRef(true),pending=useRef(false),retry=useRef<{answer:string;turn:number;id:string}|null>(null),end=useRef<HTMLDivElement>(null);
  useEffect(()=>{mounted.current=true;api('status').then(data=>{if(mounted.current){setConfigured(data.configured);setSession(data.session || data.report || null);}}).catch(e=>{if(mounted.current){setError(e.message);if(e.message==='Sign in required')setSignedIn(false);}}).finally(()=>{if(mounted.current)setBusy(false);});fetch('/api/users/career',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(mounted.current&&data?.career){if(data.career.careerPath)setRole(data.career.careerPath);if(data.career.industry)setIndustry(data.career.industry);}}).catch(()=>{});return()=>{mounted.current=false;};},[]);
  useEffect(()=>{if(session?.status!=='FINISHED'&&end.current?.parentElement)end.current.parentElement.scrollTop=end.current.parentElement.scrollHeight;},[session?.turn,busy]);
  async function run(path:string,body:unknown){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const data=await api(path,body);if(mounted.current){setSession(data.session);if(path==='turn'){setAnswer('');retry.current=null;}}}catch(e:any){if(mounted.current)setError(e.message);}finally{pending.current=false;if(mounted.current)setBusy(false);}}
  function submit(){if(!session||answer.trim().length<5||busy)return;const text=answer.trim();if(!retry.current||retry.current.answer!==text||retry.current.turn!==session.turn)retry.current={answer:text,turn:session.turn,id:crypto.randomUUID()};void run('turn',{sessionId:session.id,answer:text,expectedTurn:session.turn,requestId:retry.current.id});}
  return <section className="techInterview" aria-label="AI technical interview">
    <p className="techIntro">Practice a real conversation. Explain your approach, respond to follow-ups, and review personalized coaching. This is a simulated interview.</p>
    {error&&<p role="alert" className="techError">{error}</p>}
    {!signedIn?<p><Link href="/dashboard">Sign in</Link> to save your interview and resume later.</p>:!configured&&!session?<p className="techNotice">AI interviews are not configured yet. Your administrator must set OPENAI_API_KEY on the server.</p>:!session?<form className="techSetup" onSubmit={e=>{e.preventDefault();void run('start',{role,industry,level});}}>
      <label>Target role<input value={role} onChange={e=>setRole(e.target.value)} required minLength={2} maxLength={160} placeholder="Cloud Engineer, Security Analyst, Help Desk…" disabled={busy}/></label>
      <label>Industry<input value={industry} onChange={e=>setIndustry(e.target.value)} required minLength={2} maxLength={160} disabled={busy}/></label>
      <label>Experience level<select value={level} onChange={e=>setLevel(e.target.value)} disabled={busy}>{['Entry level','Intermediate','Senior'].map(value=><option key={value}>{value}</option>)}</select></label>
      <p>Six questions • Typed answers • Saved progress<br/>Avoid sharing passwords or confidential employer information.</p>
      <button className="d2Btn" disabled={busy||role.trim().length<2||industry.trim().length<2}>{busy?'Preparing interviewer…':'Enter the interview'}</button>
    </form>:<>
      <header className="techStatus"><div><h3>{session.role}</h3><small>{session.industry} · {session.level}</small></div><span>{session.status==='FINISHED'?'Interview complete':`${session.turn} / ${session.maxTurns} answered`}</span></header>
      <progress aria-label="Interview progress" value={session.turn} max={session.maxTurns}/>
      {session.performance&&<div className="techReport"><h3>Your coaching report · {Math.round((session.scoreAvg||0)*100)}%</h3><p>{session.performance.summary}</p><div className="techCriteria">{Object.entries(session.performance.criteria).map(([key,value])=><label key={key}>{key}<meter min={0} max={5} value={value}/><span>{value.toFixed(1)} / 5</span></label>)}</div><h4>Strengths</h4><ul>{session.performance.strengths.map(s=><li key={s}>{s}</li>)}</ul><h4>Practice next</h4><ul>{session.performance.improvements.map(s=><li key={s}>{s}</li>)}</ul><button className="d2Btn" disabled={busy} onClick={()=>{setSession(null);setAnswer('');retry.current=null;}}>Practice another interview</button><p><Link href="/dashboard">Return to dashboard</Link></p></div>}
      <div className="techTranscript" role="log" aria-label="Interview conversation" aria-live="polite">{session.transcript.map((turn,index)=><article className={`techMessage ${turn.speaker==='CANDIDATE'?'candidate':'interviewer'}`} key={index}><strong>{turn.speaker==='CANDIDATE'?'You':'AI interviewer'}</strong><p>{turn.content}</p>{turn.feedback&&<details><summary>Review answer coaching</summary><p><b>Strengths:</b> {turn.feedback.strengths.join(' ')||'No clear strengths evidenced yet.'}</p><p><b>Improve:</b> {turn.feedback.improvements.join(' ')}</p><p><b>Example stronger answer:</b> {turn.feedback.exampleAnswer}</p></details>}</article>)}{busy&&<p role="status">The interviewer is preparing your feedback…</p>}<div ref={end}/></div>
      {session.status!=='FINISHED'&&(session.nextQuestion?<form className="techAnswer" onSubmit={e=>{e.preventDefault();submit();}}><label htmlFor="tech-interview-answer">Your answer<textarea id="tech-interview-answer" value={answer} onChange={e=>setAnswer(e.target.value)} rows={5} minLength={5} maxLength={6000} required disabled={busy} placeholder="Explain your reasoning, what you would check, and why…"/></label><small>{answer.length} / 6,000 characters</small><button className="d2Btn" disabled={busy||answer.trim().length<5}>{busy?'Reviewing your answer…':'Submit answer'}</button></form>:<button className="d2Btn" disabled={busy} onClick={()=>void run('finish',{sessionId:session.id})}>{busy?'Preparing report…':'View coaching report'}</button>)}
    </>}
  </section>;
}
